sylius_resource:
    resources:
        positibe.enum:
            driver: doctrine/orm
            templates: PositibeEnumBundle:Enum
            classes:
                model: Positibe\Bundle\EnumBundle\Entity\Enum
                controller: Positibe\Bundle\EnumBundle\Controller\EnumController
                repository: Positibe\Bundle\EnumBundle\Repository\EnumRepository
        positibe.enum_type:
            driver: doctrine/orm
            templates: PositibeEnumBundle:EnumType
            classes:
                model: Positibe\Bundle\EnumBundle\Entity\EnumType
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository