services:
    Positibe\Bundle\EnumBundle\Initializer\EnumInitializer:
        public: true
        arguments: ["%positibe_enum.enum_types%","@doctrine.orm.entity_manager"]

    Positibe\Bundle\EnumBundle\Command\EnumInitializerCommand:
        tags:
            - { name: console.command }
