<?php
/**
 * This file was generated by PcabreusGeneratorBundle
 */

namespace Positibe\Bundle\EnumBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class EnumFormType
 * @package Positibe\Bundle\EnumBundle\Form\Type
 */
class EnumFormType extends AbstractType
{
    private $locales;

    public function __construct($locales = [])
    {
        $this->locales = $locales;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', null, ['label' => 'enum.form.name_label'])
            ->add('position', null, ['label' => 'enum.form.position_label', 'required' => false])
            ->add('text', null, ['label' => 'enum.form.text_label'])
            ->add('type', null, ['label' => 'enum.form.type_label']);
        if (count($this->locales) > 0) {
            $builder->add(
                'locale',
                ChoiceType::class,
                array(
                    'label' => 'enum.form.locale_label',
                    'choices' => array_combine($this->locales, $this->locales),
                    'translation_domain' => 'messages',
                )
            );
        }
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class' => 'Positibe\Bundle\EnumBundle\Entity\Enum',
                'translation_domain' => 'PositibeEnumBundle',
            )
        );
    }
}
