<?php
/**
 * This file was generated by PcabreusGeneratorBundle
 */

namespace Positibe\Bundle\EnumBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * Class EnumFormType
 * @package Positibe\Bundle\EnumBundle\Form\Type
 */
class EnumFormType extends AbstractType
{
    private $locales;

    public function __construct($locales = [])
    {
        $this->locales = $locales;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', null, array('label' => 'enum.form.name_label'))
            ->add('text', null, array('label' => 'enum.form.text_label'))
            ->add('type', null, array('label' => 'enum.form.type_label', 'property' => 'getUpperName'));

            if (count($this->locales) > 0) {
                $builder->add(
                    'locale',
                    'choice',
                    array(
                        'label' => 'enum.form.locale_label',
                        'choices' => array_combine($this->locales, $this->locales),
                        'translation_domain' => 'messages'
                    )
                );
            }
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class' => 'Positibe\Bundle\EnumBundle\Entity\Enum',
                'translation_domain' => 'PositibeEnumBundle'
            )
        );
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'positibe_enum';
    }
}
