positibe_enum_type_create:
    path: /new
    methods: [GET, POST]
    defaults:
        _controller: positibe.controller.enum_type:createAction
        _sylius:
            redirect:
                route: positibe_enum_type_show
                parameters: {name: resource.name}

positibe_enum_type_show:
    path: /{name}
    methods: [GET]
    defaults:
        _controller: positibe.controller.enum_type:showAction
        _sylius:
            criteria:
                name: $name

positibe_enum_type_update:
    path: /{name}/edit
    methods: [GET, PUT]
    defaults:
        _controller: positibe.controller.enum_type:updateAction
        _sylius:
            criteria:
                name: $name
            redirect:
                route: positibe_enum_type_show
                parameters: {name: resource.name}

positibe_enum_type_delete:
    path: /{name}
    methods: [DELETE]
    defaults:
        _controller: positibe.controller.enum_type:deleteAction
        _sylius:
            criteria:
                name: $name
                deletable: true
            redirect:
                route: positibe_enum_type_index
                parameters: {}

positibe_enum_type_index:
    path: /
    methods: [GET]
    defaults:
        _controller: positibe.controller.enum_type:indexAction
        _sylius:
            sortable: true
